plugins:
    - jemoji
    - jekyll-octicons
exclude:
    - 'README.md'
    - 'screenshot.png'
    - 'Dockerfile'
    - 'Makefile'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'node_modules'
    - 'package.json'
    - 'package-lock.json'
    - 'vendor'
sass:
    style: compressed
